from __future__ import annotations

from PySide6.QtCore import Qt
from PySide6.QtWidgets import QCheckBox, QComboBox, QFormLayout, QHBoxLayout, QLabel, QLineEdit, QPlainTextEdit, QSlider, QVBoxLayout

from ..color_ui import LightingPanel
from ..config import device
from .common import KINDS, box, button, integer


class DevicePage:
    def build_device(self):
        layout = self.page(self.t("Tu dispositivo", "Your device"), self.t("Conexión local, controles de pantalla e iluminación ambiental.",
                                                                           "Local connection, display controls and ambient lighting."))
        card = box()
        form = QFormLayout(card)
        self.device_name, self.device_ip, self.device_mac = QLineEdit(), QLineEdit(), QLineEdit()
        self.device_id = QLineEdit()
        self.device_port, self.device_token = QLineEdit(), QLineEdit()
        self.device_port.setPlaceholderText(self.t("Auto (80 o 9000)", "Auto (80 or 9000)"))
        self.device_token.setPlaceholderText(self.t("Token local de la app Divoom", "Local token from the Divoom app"))
        form.addRow(self.t("Nombre", "Name"), self.device_name)
        form.addRow("IP", self.device_ip)
        form.addRow("MAC", self.device_mac)
        form.addRow("DeviceId", self.device_id)
        form.addRow(self.t("Puerto", "Port"), self.device_port)
        form.addRow(self.t("Token local", "Local token"), self.device_token)
        row = QHBoxLayout()
        row.addWidget(button(self.t("Guardar conexión", "Save connection"), self.save_device, True))
        row.addWidget(button(self.t("Añadir dispositivo…", "Add device…"), self.add_device))
        row.addWidget(button(self.t("Buscar en LAN", "Scan LAN"), lambda: self.scan(False)))
        row.addWidget(button(self.t("Buscar vía Divoom", "Discover via Divoom"), lambda: self.scan(True)))
        row.addWidget(button(self.t("Comprobar", "Check"), lambda: self.job("health")))
        form.addRow(row)
        layout.addWidget(card)
        controls = QHBoxLayout()
        display = box()
        f = QFormLayout(display)
        self.brightness = QSlider(Qt.Orientation.Horizontal)
        self.brightness.setRange(0, 100)
        self.brightness.setValue(60)
        self.brightness_label = QLabel("60%")
        self.brightness.valueChanged.connect(lambda n: self.brightness_label.setText(f"{n}%"))
        row = QHBoxLayout()
        row.addWidget(self.brightness)
        row.addWidget(self.brightness_label)
        f.addRow(self.t("Brillo de pantallas", "Display brightness"), row)
        f.addRow(button(self.t("Aplicar brillo", "Apply brightness"), lambda: self.command("Channel/SetBrightness", Brightness=self.brightness.value())))
        row = QHBoxLayout()
        row.addWidget(button(self.t("Encender", "Turn on"), lambda: self.command("Channel/OnOffScreen", OnOff=1)))
        row.addWidget(button(self.t("Apagar", "Turn off"), lambda: self.command("Channel/OnOffScreen", OnOff=0)))
        f.addRow(row)
        self.hour24 = QCheckBox(self.t("Formato 24 horas", "24-hour format"))
        self.hour24.setChecked(True)
        self.celsius = QCheckBox(self.t("Temperatura en °C", "Temperature in °C"))
        self.celsius.setChecked(True)
        self.mirror = QCheckBox(self.t("Modo espejo", "Mirror mode"))
        f.addRow(self.hour24)
        f.addRow(self.celsius)
        f.addRow(self.mirror)
        f.addRow(button(self.t("Aplicar preferencias", "Apply preferences"), self.apply_preferences))
        f.addRow(button(self.t("Sincronizar hora del PC", "Sync computer time"), self.sync_time))
        controls.addWidget(display)
        layout.addLayout(controls)
        rgb = box()
        rgb_layout = QVBoxLayout(rgb)
        self.lighting = LightingPanel(t=self.t)
        self.lighting.applyRequested.connect(self.apply_rgb)
        rgb_layout.addWidget(self.lighting)
        layout.addWidget(rgb)
        layout.addStretch()

    def build_tools(self):
        layout = self.page(self.t("Herramientas y avisos", "Tools and notifications"), self.t(
            "Las herramientas nativas pausan el reenvío de este dispositivo. Restaura la composición al terminar.",
            "Native tools pause this device's automatic uploads. Restore your layout when finished."))
        tabs = QHBoxLayout()
        card = box()
        form = QFormLayout(card)
        self.tool_panel = QComboBox()
        self.tool_panel.addItem(self.t("Global · compatible", "Global · compatible"), None)
        for i in range(5):
            self.tool_panel.addItem(self.t(f"Pantalla {i+1} · experimental", f"Screen {i+1} · experimental"), i + 1)
        form.addRow(self.t("Destino herramientas", "Tool target"), self.tool_panel)
        self.timer_minutes = integer(0, 999, 25)
        self.timer_seconds = integer(0, 59)
        row = QHBoxLayout()
        row.addWidget(self.timer_minutes)
        row.addWidget(QLabel("min"))
        row.addWidget(self.timer_seconds)
        row.addWidget(QLabel("s"))
        form.addRow(self.t("Cuenta atrás", "Timer"), row)
        row = QHBoxLayout()
        row.addWidget(button(self.t("Iniciar", "Start"), lambda: self.native_tool("Tools/SetTimer", Minute=self.timer_minutes.value(), Second=self.timer_seconds.value(), Status=1)))
        row.addWidget(button(self.t("Detener", "Stop"), lambda: self.native_tool("Tools/SetTimer", Minute=0, Second=0, Status=0)))
        form.addRow(row)
        row = QHBoxLayout()
        for es, en, status in [("Iniciar", "Start", 1), ("Parar", "Stop", 0), ("Reiniciar", "Reset", 2)]:
            row.addWidget(button(self.t(es, en), lambda checked=False, value=status: self.native_tool("Tools/SetStopWatch", Status=value)))
        form.addRow(self.t("Cronómetro", "Stopwatch"), row)
        self.red_score, self.blue_score = integer(0, 999), integer(0, 999)
        row = QHBoxLayout()
        row.addWidget(self.red_score)
        row.addWidget(self.blue_score)
        form.addRow(self.t("Marcador rojo / azul", "Red / blue score"), row)
        form.addRow(button(self.t("Mostrar marcador", "Show scoreboard"), lambda: self.native_tool("Tools/SetScoreBoard", RedScore=self.red_score.value(), BlueScore=self.blue_score.value())))
        row = QHBoxLayout()
        row.addWidget(button(self.t("Medidor de sonido", "Noise meter"), lambda: self.native_tool("Tools/SetNoiseStatus", NoiseStatus=1)))
        row.addWidget(button(self.t("Parar medidor", "Stop meter"), lambda: self.native_tool("Tools/SetNoiseStatus", NoiseStatus=0)))
        form.addRow(row)
        form.addRow(button(self.t("Restaurar composición", "Restore layout"), lambda: self.job("resume"), True))
        tabs.addWidget(card, 1)
        notices = box()
        form = QFormLayout(notices)
        self.notice_text = QPlainTextEdit()
        self.notice_text.setMaximumHeight(90)
        self.notice_text.setPlaceholderText(self.t("Tu mensaje…", "Your message…"))
        self.notice_panel = integer(1, 5, 1)
        self.notice_seconds = integer(5, 3600, 15)
        self.notice_buzzer = QCheckBox(self.t("Aviso sonoro", "Sound alert"))
        form.addRow(self.t("Mensaje temporal", "Temporary message"), self.notice_text)
        form.addRow(self.t("Pantalla", "Screen"), self.notice_panel)
        form.addRow(self.t("Duración (s)", "Duration (s)"), self.notice_seconds)
        form.addRow(self.notice_buzzer)
        form.addRow(button(self.t("Enviar aviso", "Send notification"), self.send_notice, True))
        form.addRow(button(self.t("Probar pitido", "Test buzzer"), lambda: self.command("Device/PlayBuzzer", ActiveTimeInCycle=150, OffTimeInCycle=150, PlayTotalTime=600)))
        form.addRow(self.hint(self.t("El aviso restaura después la imagen o widget anterior. Elige una pantalla gestionada por Studio.",
                                    "The notification restores the previous image or widget afterward. Choose a screen managed by Studio.")))
        tabs.addWidget(notices, 1)
        layout.addLayout(tabs)
        native = box()
        f = QFormLayout(native)
        self.clock_id = integer(0, 2147483647, 625)
        self.independence = integer(0, 2147483647)
        self.native_panel = integer(1, 5, 1)
        f.addRow(QLabel(self.t("Relojes nativos · experimental", "Native clocks · experimental")))
        f.addRow("ClockId", self.clock_id)
        f.addRow("LcdIndependence", self.independence)
        f.addRow(self.t("Pantalla", "Screen"), self.native_panel)
        row = QHBoxLayout()
        row.addWidget(button(self.t("Consultar catálogo / IDs", "Read catalog / IDs"), lambda: self.job("catalog")))
        row.addWidget(button(self.t("Aplicar reloj individual", "Apply individual clock"), self.set_native_clock))
        row.addWidget(button(self.t("Aplicar reloj completo", "Apply whole clock"), lambda: self.command("Channel/Set5LcdWholeClockId", pause=True, ClockId=self.clock_id.value())))
        f.addRow(row)
        f.addRow(self.hint(self.t("La consulta usa la nube Divoom y necesita DeviceId. La respuesta aparece en Actividad. No todos los relojes funcionan en todos los firmwares.",
                                 "The query uses Divoom cloud and requires DeviceId. Results appear in Activity. Clock compatibility depends on firmware.")))
        layout.addWidget(native)
        layout.addStretch()
