from __future__ import annotations

from PySide6.QtCore import QTime, QUrl
from PySide6.QtGui import QDesktopServices
from PySide6.QtWidgets import QCheckBox, QComboBox, QFormLayout, QGridLayout, QHBoxLayout, QLabel, QListWidget, QPlainTextEdit, QTableWidget, QTimeEdit, QVBoxLayout

from ..config import device
from .common import KINDS, box, button, integer


class PanelPages:
    def build_scenes(self):
        layout = self.page(self.t("Escenas", "Scenes"), self.t("Guarda composiciones completas y cambia de ambiente con un clic.",
                                                                 "Save complete layouts and change the mood with one click."))
        card = box()
        row = QHBoxLayout(card)
        self.scene_list = QListWidget()
        self.scene_list.setMinimumHeight(250)
        row.addWidget(self.scene_list, 2)
        actions = QVBoxLayout()
        actions.addWidget(button(self.t("Guardar composición actual…", "Save current layout…"), self.new_scene, True))
        actions.addWidget(button(self.t("Aplicar escena", "Apply scene"), self.apply_scene))
        actions.addWidget(button(self.t("Renombrar", "Rename"), self.rename_scene))
        actions.addWidget(button(self.t("Eliminar", "Delete"), self.delete_scene))
        actions.addStretch()
        row.addLayout(actions, 1)
        layout.addWidget(card)
        rotation = box()
        form = QFormLayout(rotation)
        self.rotation_enabled = QCheckBox(self.t("Rotar las escenas marcadas", "Rotate checked scenes"))
        self.rotation_seconds = integer(30, 86400, 300)
        self.rotation_seconds.setSuffix(" s")
        form.addRow(self.rotation_enabled)
        form.addRow(self.t("Cambiar cada", "Switch every"), self.rotation_seconds)
        form.addRow(self.hint(self.t("Marca escenas en la lista. La rotación sigue su orden y necesita la actualización automática activada.",
                                    "Check scenes in the list. Rotation follows list order and requires automatic updates.")))
        form.addRow(button(self.t("Guardar rotación", "Save rotation"), self.save_rotation))
        layout.addWidget(rotation)
        layout.addStretch()

    def build_schedules(self):
        layout = self.page(self.t("Horarios", "Schedules"), self.t("Programa escenas, brillo y descanso de las pantallas. Se usa la hora local del PC.",
                                                                   "Schedule scenes, brightness and display sleep using your computer's local time."))
        self.schedule_table = QTableWidget(0, 6)
        self.schedule_table.setHorizontalHeaderLabels([self.t("Hora", "Time"), self.t("Días", "Days"), self.t("Dispositivo", "Device"), self.t("Acción", "Action"), self.t("Valor", "Value"), self.t("Activo", "Enabled")])
        self.schedule_table.horizontalHeader().setStretchLastSection(True)
        self.schedule_table.setSelectionBehavior(QTableWidget.SelectionBehavior.SelectRows)
        self.schedule_table.setEditTriggers(QTableWidget.EditTrigger.NoEditTriggers)
        self.schedule_table.setMinimumHeight(230)
        layout.addWidget(self.schedule_table)
        card = box()
        f = QFormLayout(card)
        self.schedule_time = QTimeEdit(QTime(22, 0))
        self.schedule_time.setDisplayFormat("HH:mm")
        self.schedule_days = QComboBox()
        self.schedule_days.addItem(self.t("Todos los días", "Every day"), list(range(7)))
        self.schedule_days.addItem(self.t("Lunes a viernes", "Weekdays"), list(range(5)))
        self.schedule_days.addItem(self.t("Sábado y domingo", "Weekends"), [5, 6])
        self.schedule_action = QComboBox()
        for es, en, key in [("Aplicar escena", "Apply scene", "scene"), ("Brillo", "Brightness", "brightness"), ("Apagar pantallas", "Displays off", "off"), ("Encender pantallas", "Displays on", "on")]:
            self.schedule_action.addItem(self.t(es, en), key)
        self.schedule_scene = QComboBox()
        self.schedule_brightness = integer(0, 100, 20)
        f.addRow(self.t("Hora", "Time"), self.schedule_time)
        f.addRow(self.t("Días", "Days"), self.schedule_days)
        f.addRow(self.t("Acción", "Action"), self.schedule_action)
        f.addRow(self.t("Escena (si corresponde)", "Scene (when applicable)"), self.schedule_scene)
        f.addRow(self.t("Brillo (si corresponde)", "Brightness (when applicable)"), self.schedule_brightness)
        row = QHBoxLayout()
        row.addWidget(button(self.t("Añadir al dispositivo seleccionado", "Add for selected device"), self.add_schedule, True))
        row.addWidget(button(self.t("Activar / desactivar seleccionado", "Toggle selected"), self.toggle_schedule))
        row.addWidget(button(self.t("Eliminar seleccionado", "Delete selected"), self.delete_schedule))
        f.addRow(row)
        layout.addWidget(card)
        layout.addWidget(self.hint(self.t("Studio debe estar abierto y la actualización automática activa. Los horarios no ejecutados mientras el PC estaba apagado no se recuperan.",
                                         "Studio must be running with automatic updates enabled. Schedules missed while the computer was off are not replayed.")))
        layout.addStretch()

    def build_activity(self):
        layout = self.page(self.t("Actividad", "Activity"), self.t("Respuestas del dispositivo, envíos y errores. Un comando aceptado aún requiere comprobar el efecto en pantalla.",
                                                                   "Device responses, uploads and errors. Accepted commands still need visual verification on the device."))
        self.activity = QPlainTextEdit()
        self.activity.setReadOnly(True)
        self.activity.document().setMaximumBlockCount(1500)
        self.activity.setMinimumHeight(450)
        layout.addWidget(self.activity, 1)
        row = QGridLayout()
        row.addWidget(button(self.t("Consultar ajustes", "Read settings"), lambda: self.command("Channel/GetAllConf")), 0, 0)
        row.addWidget(button(self.t("Consultar canales", "Read channels"), lambda: self.command("Channel/GetIndex")), 0, 1)
        row.addWidget(button(self.t("Abrir carpeta de datos", "Open data folder"), lambda: QDesktopServices.openUrl(QUrl.fromLocalFile(str(self.store.root)))), 0, 2)
        row.addWidget(button(self.t("Limpiar vista", "Clear view"), self.activity.clear), 1, 0)
        row.addWidget(button(self.t("Reiniciar dispositivo…", "Reboot device…"), self.reboot), 1, 1)
        layout.addLayout(row)

    def build_settings(self):
        layout = self.page(self.t("Ajustes de Studio", "Studio settings"), self.t("Tu biblioteca y preferencias se guardan separadas de Divoom Keeper original.",
                                                                                "Your library and preferences are stored separately from the original Divoom Keeper."))
        card = box()
        f = QFormLayout(card)
        self.language = QComboBox()
        self.language.addItem("English", "en")
        self.language.addItem("Español", "es")
        self.theme = QComboBox()
        self.theme.addItem(self.t("Oscuro", "Dark"), "dark")
        self.theme.addItem(self.t("Claro", "Light"), "light")
        self.startup = QCheckBox(self.t("Iniciar Studio al iniciar sesión", "Start Studio at login"))
        self.resend = QCheckBox(self.t("Restaurar al iniciar (dispositivos automáticos)", "Restore on startup (automatic devices)"))
        self.interval = integer(1, 10080, 60)
        self.interval.setSuffix(" min")
        self.quality = integer(30, 100, 85)
        self.speed = integer(1, 10000, 100)
        self.speed.setSuffix(" ms")
        data = self.store.snapshot()
        self.language.setCurrentIndex(self.language.findData(data["language"]))
        self.theme.setCurrentIndex(self.theme.findData(data["theme"]))
        self.startup.setChecked(data["startup"])
        self.resend.setChecked(data["resend_on_startup"])
        f.addRow(self.t("Idioma · al reiniciar", "Language · after restart"), self.language)
        f.addRow(self.t("Apariencia", "Appearance"), self.theme)
        f.addRow(self.startup)
        f.addRow(self.resend)
        f.addRow(self.t("Reenvío de seguridad", "Recovery resend interval"), self.interval)
        f.addRow(self.t("Calidad JPEG", "JPEG quality"), self.quality)
        f.addRow(self.t("Duración por fotograma GIF", "GIF frame duration"), self.speed)
        f.addRow(button(self.t("Guardar ajustes", "Save settings"), self.save_settings, True))
        f.addRow(self.hint(self.t("Intervalo, calidad y velocidad corresponden al dispositivo seleccionado. Los widgets tienen su propio intervalo de actualización.",
                                 "Interval, quality and speed apply to the selected device. Widgets have individual refresh intervals.")))
        layout.addWidget(card)
        copies = box()
        v = QVBoxLayout(copies)
        v.addWidget(QLabel(self.t("Biblioteca y copias de seguridad", "Library and backups")))
        v.addWidget(self.hint(str(self.store.root)))
        row = QHBoxLayout()
        row.addWidget(button(self.t("Exportar copia portátil…", "Export portable backup…"), self.export_bundle))
        row.addWidget(button(self.t("Importar copia…", "Import backup…"), self.import_bundle))
        row.addWidget(button(self.t("Abrir biblioteca", "Open library"), lambda: QDesktopServices.openUrl(QUrl.fromLocalFile(str(self.store.media_dir)))))
        v.addLayout(row)
        v.addWidget(self.hint(self.t("La copia incluye perfiles, escenas, horarios y archivos locales. Puede contener direcciones de calendarios privados.",
                                    "Backups include profiles, scenes, schedules and local files. They may contain private calendar URLs.")))
        layout.addWidget(copies)
        layout.addStretch()
